
import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Link } from 'react-router-dom';
import GarageSettings from '@/components/settings/GarageSettings';
import GstSettings from '@/components/settings/GstSettings';
import GarageServicesManager from '@/components/garageServices/GarageServicesManager';
import { FileText, Settings as SettingsIcon, Wrench } from 'lucide-react';

const Settings = () => {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Settings</h1>
        <p className="text-muted-foreground">
          Configure your garage management system.
        </p>
      </div>

      <Tabs defaultValue="general">
        <TabsList className="mb-4">
          <TabsTrigger value="general">General</TabsTrigger>
          <TabsTrigger value="services">Services</TabsTrigger>
          <TabsTrigger value="taxes">Taxes & GST</TabsTrigger>
          <TabsTrigger value="documents">Documents</TabsTrigger>
        </TabsList>
        
        <TabsContent value="general" className="space-y-4">
          <GarageSettings />
        </TabsContent>
        
        <TabsContent value="services" className="space-y-4">
          <GarageServicesManager />
        </TabsContent>
        
        <TabsContent value="taxes" className="space-y-4">
          <GstSettings />
        </TabsContent>
        
        <TabsContent value="documents" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Document Templates</CardTitle>
              <CardDescription>
                Configure templates for various documents generated by the system
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                <Link to="/settings/invoice" className="block">
                  <Card className="hover:bg-muted/50 cursor-pointer transition-colors">
                    <CardContent className="pt-6">
                      <div className="flex items-start gap-3">
                        <div className="bg-primary/10 p-2 rounded-md">
                          <FileText className="h-5 w-5 text-primary" />
                        </div>
                        <div>
                          <h3 className="font-medium">Invoice Settings</h3>
                          <p className="text-sm text-muted-foreground mt-1">
                            Configure invoice template, logo, and payment terms
                          </p>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </Link>
                
                <Card className="opacity-50">
                  <CardContent className="pt-6">
                    <div className="flex items-start gap-3">
                      <div className="bg-primary/10 p-2 rounded-md">
                        <SettingsIcon className="h-5 w-5 text-primary" />
                      </div>
                      <div>
                        <h3 className="font-medium">Job Card Templates</h3>
                        <p className="text-sm text-muted-foreground mt-1">
                          Coming soon: Configure job card templates
                        </p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
                
                <Card className="opacity-50">
                  <CardContent className="pt-6">
                    <div className="flex items-start gap-3">
                      <div className="bg-primary/10 p-2 rounded-md">
                        <SettingsIcon className="h-5 w-5 text-primary" />
                      </div>
                      <div>
                        <h3 className="font-medium">Estimate Templates</h3>
                        <p className="text-sm text-muted-foreground mt-1">
                          Coming soon: Configure estimate templates
                        </p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default Settings;
